<a href="https://colab.research.google.com/github/Abhii009/Learn-Python/blob/main/Day10numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
#filter | array me se valuse nikalna jo apne chaiye
arr = np.array([10,20,3,4,50,900])
arr_f = arr[arr>20]
print(arr_f)

[ 50 900]


In [9]:
arr = np.array([200,300,10,38,47,5657,34,60])
arr_f = arr[arr != 60]
print(arr_f)

[ 200  300   10   38   47 5657   34]


In [15]:
arr = np.arange(20)
arr_f = arr[(arr > 10) & (arr < 20)]
print(arr_f)

[11 12 13 14 15 16 17 18 19]


In [16]:
import numpy as np
arr = np.array([10,20,30,5,8,0,2,54,15,3,2,18,8])
arr_f = arr[(arr>10) & (arr<20)]
print(arr_f)

[15 18]


In [17]:
#fancy indexing
arr = np.array([10,20,40,5,7,2,800])
print(arr)
arr_f = arr[[0,2]] #0 index value, 2 index value
print(arr_f)


[ 10  20  40   5   7   2 800]
[10 40]


In [23]:
#where
arr = np.array([10,20,3,4,5,88,900])
print(arr)
arr_w=np.where(arr>9,"True","false")
print(arr_w)

#question 10 -20 -> | +2


[ 10  20   3   4   5  88 900]
['True' 'True' 'false' 'false' 'false' 'True' 'True']


In [26]:
import numpy as np

arr = np.array([10,20,3,4,5,88,900])
print(arr)
new_arr = np.where((arr >= 10) & (arr <= 20), arr+2, arr*2,)

print(new_arr)

[ 10  20   3   4   5  88 900]
[  12   22    6    8   10  176 1800]


In [29]:
#adding and removing
arr1 = np.array([10,30,50])
arr2 = np.array([1,2,3])

#concatenate
arr_arr2 = np.concatenate((arr1,arr2))
print(arr_arr2)

#concatenate using 2d
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
arr1_arr2 = np.concatenate((arr1,arr2))
print(arr1_arr2)



[10 30 50  1  2  3]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [34]:
#v-stack | vertically join | roe vise
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr_h = np.vstack((arr1,arr2))
print(arr_h)

[[1 2 3]
 [4 5 6]]


In [33]:
# H-stack | Horizontally stack
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr_h = np.hstack((arr1,arr2))
print(arr_h)

[1 2 3 4 5 6]


In [35]:
#useful function
arr = np.array([10,20,30,40])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

25.0
25.0
11.180339887498949
125.0
10
40


In [37]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(np.sum(arr)) # sum
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))

30
2
10
6.0
6.0


In [38]:
arr = ([10,20,30,40])
print('Mean:' ,np.mean(arr)) #mean
print('Median:' ,np.median(arr)) #median
print('Standard Deviation:' ,np.std(arr)) #standard deviation
print('Variance:' ,np.var(arr)) #variance
print(np.min(arr)) #min
print(np.max(arr)) #max

Mean: 25.0
Median: 25.0
Standard Deviation: 11.180339887498949
Variance: 125.0
10
40


In [39]:
# 1. np.sum(a) -> Sum of all elements
# 2. np.mean(a) -> Average = Sum of elements / Number of elements
# 3. np.median(a) -> Middle value after sorting
# 4. np.min(a) -> Smallest value in array
# 5. np.max(a) -> Largest value in array
# 6. np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length
# 7. np.std(a) -> Standard Deviation = √Variance -> Measures spread of data
# 8. np.prod(a) -> Multiplication of all elements
# 9. np.cumsum(a) -> Cumulative (running) sum
# 10. np.cumprod(a) -> Cumulative (running) product
# 11. np.argmin(a) -> Index position of minimum value
# 12. np.argmax(a) -> Index position of maximum value
# 13. np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)
# 14. np.unique(a) -> Returns unique values only -> Removes duplicates
# 15. np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median
# 16. np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%
# 17. np.ptp(a) -> Range = Max - Min
# 18. np.any(a) -> True if at least one value is True


In [60]:
#1 sum
arr = ([10,20,30,40])
arr = np.sum(arr)
__builtins__.print(arr)

100


In [62]:
#percentil
import numpy as np
arr =  np.array([10,20,30,5,55,66])
__builtins__.print(np.percentile(arr,20))

10.0


In [64]:
import numpy as np
from scipy import stats

arr = np.array([2,2,3,4,4,4,5])

result = stats.mode(arr)

__builtins__.print("Mode :", result.mode)
__builtins__.print("Frequency :", result.count)

Mode : 4
Frequency : 3
