<a href="https://colab.research.google.com/github/Abhii009/Learn-Python/blob/main/Day10numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
#filter | array me se valuse nikalna jo apne chaiye
arr = np.array([10,20,3,4,50,900])
arr_f = arr[arr>20]
print(arr_f)

[ 50 900]


In [9]:
arr = np.array([200,300,10,38,47,5657,34,60])
arr_f = arr[arr != 60]
print(arr_f)

[ 200  300   10   38   47 5657   34]


In [15]:
arr = np.arange(20)
arr_f = arr[(arr > 10) & (arr < 20)]
print(arr_f)

[11 12 13 14 15 16 17 18 19]


In [16]:
import numpy as np
arr = np.array([10,20,30,5,8,0,2,54,15,3,2,18,8])
arr_f = arr[(arr>10) & (arr<20)]
print(arr_f)

[15 18]


In [17]:
#fancy indexing
arr = np.array([10,20,40,5,7,2,800])
print(arr)
arr_f = arr[[0,2]] #0 index value, 2 index value
print(arr_f)


[ 10  20  40   5   7   2 800]
[10 40]


In [23]:
#where
arr = np.array([10,20,3,4,5,88,900])
print(arr)
arr_w=np.where(arr>9,"True","false")
print(arr_w)

#question 10 -20 -> | +2


[ 10  20   3   4   5  88 900]
['True' 'True' 'false' 'false' 'false' 'True' 'True']


In [26]:
import numpy as np

arr = np.array([10,20,3,4,5,88,900])
print(arr)
new_arr = np.where((arr >= 10) & (arr <= 20), arr+2, arr*2,)

print(new_arr)

[ 10  20   3   4   5  88 900]
[  12   22    6    8   10  176 1800]


In [29]:
#adding and removing
arr1 = np.array([10,30,50])
arr2 = np.array([1,2,3])

#concatenate
arr_arr2 = np.concatenate((arr1,arr2))
print(arr_arr2)

#concatenate using 2d
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
arr1_arr2 = np.concatenate((arr1,arr2))
print(arr1_arr2)



[10 30 50  1  2  3]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [32]:
#v-stack | vertically join | roe vise
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr_h = np.vstack((arr1,arr2))
print(arr_h)

[[1 2 3]
 [4 5 6]]


In [33]:
# H-stack | Horizontally stack
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr_h = np.hstack((arr1,arr2))
print(arr_h)

[1 2 3 4 5 6]
