<a href="https://colab.research.google.com/github/Abhii009/Learn-Python/blob/main/Day8numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:

l = [1,2,3]
print(l)
# array
arr = np.array(l)
print(arr)

# print("hello")

[1, 2, 3]
[1 2 3]


In [20]:
#numpy list
import numpy as np
import time as t

print(t.time())
# #for list
# start =  time.time()
# sum1 = 0
# for i in range(10000):
#   sum1 += i*2
# end = time.time()

# print("for list", sum1,end-start)

# #for numpy | array | array works on every element | element wise
# start1 = time.time()
# sum2 = 0
# arr = np.arange(100000)*2
# sum2 = arr.sum()
# end1 = time.time()

# print("for numpy", sum2,end1-start1)



1781857698.9798849


In [25]:
#zeros
import numpy as np

#array 1d
arr = np.zeros(10)
print(arr)

#2d
arr1 = np.zeros((3,3)) #row and second colloums
print(arr1)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#ones
#aray1d
arr = np.ones(5)
print(arr)

#array 2d
arr1 = np.ones((3,3))
print(arr1)


[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
#full
#arr 1d
arr = np.full(5,8)
print(arr)

#arr 2d
arr1 = np.full((3,3),5)
print( arr1)

#array 3d
arr2 = np.full((3,4,5),7)
print(arr2)



[8 8 8 8 8]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]

 [[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]

 [[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]]


In [47]:
#shape
arr = np.zeros(6) #6 zeros
print(arr)
print(arr.shape) #6
print(arr.ndim) #1d array
print(arr.size) #6
print(arr.dtype) #float

#2d
print("2d ones start")
arr1 = np.zeros((3,3))
print(arr1)
print(arr1.shape) #3,3
print(arr1.ndim) #2d array
print(arr1.size) #9
print(arr1.dtype) #float

[0. 0. 0. 0. 0. 0.]
(6,)
1
6
float64
2d ones start
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
2
9
float64
