<a href="https://colab.research.google.com/github/Abhii009/Learn-Python/blob/main/Day8numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:

l = [1,2,3]
print(l)
# array
arr = np.array(l)
print(arr)

# print("hello")

[1, 2, 3]
[1 2 3]


In [20]:
#numpy list
import numpy as np
import time as t

print(t.time())
# #for list
# start =  time.time()
# sum1 = 0
# for i in range(10000):
#   sum1 += i*2
# end = time.time()

# print("for list", sum1,end-start)

# #for numpy | array | array works on every element | element wise
# start1 = time.time()
# sum2 = 0
# arr = np.arange(100000)*2
# sum2 = arr.sum()
# end1 = time.time()

# print("for numpy", sum2,end1-start1)



1781857698.9798849


In [25]:
#zeros
import numpy as np

#array 1d
arr = np.zeros(10)
print(arr)

#2d
arr1 = np.zeros((3,3)) #row and second colloums
print(arr1)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#ones
#aray1d
arr = np.ones(5)
print(arr)

#array 2d
arr1 = np.ones((3,3))
print(arr1)


[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
#full
#arr 1d
arr = np.full(5,8)
print(arr)

#arr 2d
arr1 = np.full((3,3),5)
print( arr1)

#array 3d
arr2 = np.full((3,4,5),7)
print(arr2)



[8 8 8 8 8]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]

 [[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]

 [[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]]


In [48]:
#shape
arr = np.zeros(6) #6 zeros
print(arr)
print(arr.shape) #6
print(arr.ndim) #1d array
print(arr.size) #6
print(arr.dtype) #float

#2d
print("2d ones start")
arr1 = np.zeros((3,3))
print(arr1)
print(arr1.shape) #3,3
print(arr1.ndim) #2d array
print(arr1.size) #9
print(arr1.dtype) #float



[0. 0. 0. 0. 0. 0.]
(6,)
1
6
float64
2d ones start
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
2
9
float64


In [50]:

#ones
print("ones start")
arr2 = np.ones((3,3))
print(arr2)
print(arr2.shape) #3,3
print(arr2.ndim) #2d array
print(arr2.size) #9
print(arr2.dtype) #float

ones start
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
2
9
float64


In [52]:
#twos
print("twos start")
arr3 = np.full((3,3),2)
print(arr3)
print(arr3.shape) #3,3
print(arr3.ndim) #2d
print (arr3.size) #9
print(arr3.dtype) #int


twos start
[[2 2 2]
 [2 2 2]
 [2 2 2]]
(3, 3)
2
9
int64


In [73]:
#reshape
#1d

arr = np.arange(6)

print(arr)

#2d
arr1 = arr.reshape(2,3)  #2 rows and 3 collums
print(arr1)

#3d
arr2 = arr.reshape(1,2,3) # Fixed: (1*2*3 = 6) to match the size of arr
print(arr2)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[[0 1 2]
  [3 4 5]]]


In [82]:
#flatten
import numpy as np
#2d
arr = np.arange(9)
arr1 = arr.reshape(3,3)
print(arr1)

#flatten | 2d
arr2 = arr1.flatten()
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [98]:
#ravel
#2d
arr = np.arange(9).reshape(3,3)
print(arr)

#ravel
arr_new1 = arr1.flatten()
arr_new1[0] = 200
#print(arr.ravel())
print(arr_new1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[200   1   2   3   4   5   6   7   8]


In [122]:
#transpose  | isse arr change ho jata hai values ki line change ho jati hai
arr = np.arange(9).reshape(3,3)
print(arr)

#traspose
arr1 = arr.T
print(arr1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [130]:
#stack | stacking
import numpy as np
#v-stack | vertical stack
arr_v1 = np.arange(9, 18) # Create another array for stacking
arr_v2 = np.arange(18, 27)
arr_v = np.vstack((arr_v1, arr_v2)) # Stack arr_v1 and arr_v2 vertically
print(arr_v)
'''vstack array ko row wise stack karta hai | vertical stack array ko ek ke neeche ek
jod deta hai eeth ki tarah'''

[[ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


In [132]:
#H-stack | Horizontally stack
arr_v1 = np.arange(9, 18) # Create another array for stacking
arr_v2 = np.arange(18, 27)
arr_v = np.hstack((arr_v1, arr_v2)) # Stack arr_v1 and arr_v2 vertically
print(arr_v)
'''Horizontal stack | hstack array ko collum wise stack karta hai | ek k aage ek jod deta hai'''

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]
